#include "Keys.h"
#include <iostream>
#include <map>

namespace Kek
{
	bool KeyData::operator ==(const KeyData& o)
	{
		return index == o.index && state == o.state;
	}

	const std::map<int, const char*> stateNameMap
	{
		{STATE_RELEASE,"Release"},
		{STATE_PRESS,"Press"},
		{STATE_REPEAT,"Repeat"},
		{STATE_CLICK,"Click"}
	};
	const std::map<int, const char*> keyNameMap
	{
		{MOUSE_1,"Mouse_1"},
		{MOUSE_2,"Mouse_2"},
		{MOUSE_3,"Mouse_3"},
		{MOUSE_4,"Mouse_4"},
		{MOUSE_5,"Mouse_5"},
		{MOUSE_6,"Mouse_6"},
		{MOUSE_7,"Mouse_7"},
		{MOUSE_8,"Mouse_8"},
		{KEY_0,"0"},
		{KEY_1,"1"},
		{KEY_2,"2"},
		{KEY_3,"3"},
		{KEY_4,"4"},
		{KEY_5,"5"},
		{KEY_6,"6"},
		{KEY_7,"7"},
		{KEY_8,"8"},
		{KEY_9,"9"},
		{KEY_SPACE,"Space"},
		{KEY_APOSTROPHE,"Apostrophe"},
		{KEY_COMMA,"Comma"},
		{KEY_MINUS,"Minus"},
		{KEY_PERIOD,"Period"},
		{KEY_SLASH,"Slash"},
		{KEY_SEMICOLON,"Semicolon"},
		{KEY_EQUAL,"Equal"},
		{KEY_LEFT_BRACKET,"Left_Bracket"},
		{KEY_BACKSLASH,"Backslash"},
		{KEY_RIGHT_BRACKET,"Right_Bracket"},
		{KEY_GRAVE_ACCENT,"Grave_Accent"},
		{KEY_ESCAPE,"Escape"},
		{KEY_ENTER,"Enter"},
		{KEY_TAB,"Tab"},
		{KEY_BACKSPACE,"Backspace"},
		{KEY_INSERT,"Insert"},
		{KEY_DELETE,"Delete"},
		{KEY_RIGHT,"Right"},
		{KEY_LEFT,"Left"},
		{KEY_DOWN,"Down"},
		{KEY_UP,"Up"},
		{KEY_PAGE_UP,"Page_Up"},
		{KEY_PAGE_DOWN,"Page_Down"},
		{KEY_HOME,"Home"},
		{KEY_END,"End"},
		{KEY_CAPS_LOCK,"Caps_Lock"},
		{KEY_SCROLL_LOCK,"Scroll_Lock"},
		{KEY_NUM_LOCK,"Num_Lock"},
		{KEY_PRINT_SCREEN,"Print_Screen"},
		{KEY_PAUSE,"Pause"},
		{KEY_F1,"F1"},
		{KEY_F2,"F2"},
		{KEY_F3,"F3"},
		{KEY_F4,"F4"},
		{KEY_F5,"F5"},
		{KEY_F6,"F6"},
		{KEY_F7,"F7"},
		{KEY_F8,"F8"},
		{KEY_F9,"F9"},
		{KEY_F10,"F10"},
		{KEY_F11,"F11"},
		{KEY_F12,"F12"},
		{KEY_F13,"F13"},
		{KEY_F14,"F14"},
		{KEY_F15,"F15"},
		{KEY_F16,"F16"},
		{KEY_F17,"F17"},
		{KEY_F18,"F18"},
		{KEY_F19,"F19"},
		{KEY_F20,"F20"},
		{KEY_F21,"F21"},
		{KEY_F22,"F22"},
		{KEY_F23,"F23"},
		{KEY_F24,"F24"},
		{KEY_A,"A"},
		{KEY_B,"B"},
		{KEY_C,"C"},
		{KEY_D,"D"},
		{KEY_E,"E"},
		{KEY_F,"F"},
		{KEY_G,"G"},
		{KEY_H,"H"},
		{KEY_I,"I"},
		{KEY_J,"J"},
		{KEY_K,"K"},
		{KEY_L,"L"},
		{KEY_M,"M"},
		{KEY_N,"N"},
		{KEY_O,"O"},
		{KEY_P,"P"},
		{KEY_Q,"Q"},
		{KEY_R,"R"},
		{KEY_S,"S"},
		{KEY_T,"T"},
		{KEY_U,"U"},
		{KEY_V,"V"},
		{KEY_W,"W"},
		{KEY_X,"X"},
		{KEY_Y,"Y"},
		{KEY_Z,"Z"},
		{KEY_KP_0,"KP_0"},
		{KEY_KP_1,"KP_1"},
		{KEY_KP_2,"KP_2"},
		{KEY_KP_3,"KP_3"},
		{KEY_KP_4,"KP_4"},
		{KEY_KP_5,"KP_5"},
		{KEY_KP_6,"KP_6"},
		{KEY_KP_7,"KP_7"},
		{KEY_KP_8,"KP_8"},
		{KEY_KP_9,"KP_9"},
		{KEY_KP_DECIMAL,"KP_Decimal"},
		{KEY_KP_DIVIDE,"KP_Divide"},
		{KEY_KP_MULTIPLY,"KP_Multiply"},
		{KEY_KP_SUBTRACT,"KP_Subtract"},
		{KEY_KP_ADD,"KP_Add"},
		{KEY_KP_ENTER,"KP_Enter"},
		{KEY_KP_EQUAL,"KP_Equal"},
		{KEY_LEFT_SHIFT,"Left_Shift"},
		{KEY_LEFT_CONTROL,"Left_Control"},
		{KEY_LEFT_ALT,"Left_Alt"},
		{KEY_LEFT_SUPER,"Left_Super"},
		{KEY_RIGHT_SHIFT,"Right_Shift"},
		{KEY_RIGHT_CONTROL,"Right_Control"},
		{KEY_RIGHT_ALT,"Right_Alt"},
		{KEY_RIGHT_SUPER,"Right_Super"},
		{KEY_MENU,"Menu"},
	};
	const std::map<int, const char*> modNameMap
	{
		{MOD_SHIFT,"Shift"},
		{MOD_CONTROL,"Control"},
		{MOD_ALT,"Alt"},
		{MOD_SUPER,"Super"},
		{MOD_CAPS,"CapsLock"},
		{MOD_NUM,"NumLock"}
	};
	const std::map<int, const char*> eventNameMap
	{
		{EVENT_MOUSE_MOVE,"Mouse_Move"},
		{EVENT_SCROLL_LEFT,"Mouse_Scroll_Left"},
		{EVENT_SCROLL_RIGHT,"Mouse_Scroll_Right"},
		{EVENT_SCROLL_UP,"Mouse_Scroll_Up"},
		{EVENT_SCROLL_DOWN,"Mouse_Scroll_Down"}
	};
	const char* StateName(int state) { return stateNameMap.at(state); }
	const char* KeyName(int key) { return keyNameMap.at(key); }
	const char* ModName(int mod) { return modNameMap.at(mod); }
	const char* EventName(int event) { return eventNameMap.at(event); }
}